artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  dataset_name: "opus_books"
  raw_path: artifacts/data_ingestion/raw
  data_files:
    raw_data: artifacts/data_ingestion/raw/raw.json
    train: artifacts/data_ingestion/train.json
    validation: artifacts/data_ingestion/validation.json
    test: artifacts/data_ingestion/test.json


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ['raw.json','train.json', 'validation.json']




data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/
  data_loader: artifacts/data_transformation/data_loader
  tokenizer_file: artifacts/data_transformation/'tokenizer_{0}.json'





model_trainer:
  root_dir: artifacts/trained_model
  model_folder: weights
  model_basename: 'tmodel_'
  experiment_name': 'runs/tmodel'





model_evaluation:
      root_dir: artifacts/evaluation
      






 

